CREATE TABLE Students (
    StudentID VARCHAR(255) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Phone VARCHAR(20),
    BirthDate DATE NOT NULL,
    NationalID VARCHAR(20) NOT NULL
);

CREATE TABLE Images (
    ImageID INT PRIMARY KEY AUTO_INCREMENT,
    StudentID VARCHAR(255) NOT NULL,
    Image BLOB NOT NULL,
    ImageType VARCHAR(50) NOT NULL,
    FileName VARCHAR(255) NOT NULL,
    FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
);
