name: package_fonts
description: An example of how to use package fonts with Flutter

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.3
  http: ^0.13.3
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.17.0 <3.0.0'  # 支持空安全的最低版本


flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: lib/fonts/Lato-ThinItalic.ttf
        - asset: lib/fonts/Lato-Thin.ttf
          style: italic
  uses-material-design: true